/** monitor initial readiness 的共享上界；health 等待窗口必须覆盖这条真实执行链。 */
export const MONITOR_PROCESS_BIRTH_TIMEOUT_MS = 10_000;
export const MONITOR_TARGET_LIST_TIMEOUT_MS = 5_000;
export const MONITOR_WEBSOCKET_CONNECT_TIMEOUT_MS = 8_000;
export const MONITOR_CDP_COMMAND_TIMEOUT_MS = 5_000;
export const MONITOR_ATTACH_BATCH_SIZE = 8;
export const MONITOR_INITIAL_SYNC_TIMEOUT_MS =
  MONITOR_TARGET_LIST_TIMEOUT_MS + MONITOR_WEBSOCKET_CONNECT_TIMEOUT_MS + 3 * MONITOR_CDP_COMMAND_TIMEOUT_MS;
export const MONITOR_SPAWN_READY_WAIT_TIMEOUT_MS =
  MONITOR_PROCESS_BIRTH_TIMEOUT_MS + MONITOR_INITIAL_SYNC_TIMEOUT_MS + 2_000;
